### ISSUE TITLE
Resolve "Clickable elements too close together" mobile usability error.

### ISSUE THREAD

**Issue by pstephens** [pstephens/kingjames.bible#26]
See guidelines here: https://www.portent.com/blog/seo/dont-fail-googles-mobile-friendly-test.htm

Here's a testing tool: https://www.google.com/webmasters/tools/mobile-friendly/?url=https%3A%2F%2Fkingjames.bible

More information about the "mobile friendly badge": https://webmasters.googleblog.com/2014/11/helping-users-find-mobile-friendly-pages.html

**Comment by ghaffari273** [comment]
Google has sniffed my nerves!
My site is Responsive and I use Impressa template.
With my mobile, the site simply goes up and there's no problem, but when I test Google's Webmaster, Google says your site is not web-based, my site's rating on Google has dropped sharply, please guide.
[https://farazsms.com](https://farazsms.com)

**Comment by ghaffari273** [comment]
Google has sniffed my nerves!
My site is Responsive and I use Impressa template.
With my mobile, the site simply goes up and there's no problem, but when I test Google's Webmaster, Google says your site is not Responsive, my site's rating on Google has dropped sharply, please guide.

[https://farazsms.com](https://farazsms.com)

https://search.google.com/test/mobile-friendly?utm_source=mft&utm_medium=redirect&utm_campaign=mft-redirect&id=bOEgbtSTAiWCDCmFztZjDA

**Comment by ala-woodcom** [comment]
I Have Same problem in this site
https://ala-wood.com

**Comment by Kowsarweb** [comment]
This problem is also for me
It seems to me that nobody is answering us
my site is
https://asljens.com/category/%D8%AD%D9%85%D8%A7%D9%85-%D9%88-%D8%B3%D8%B1%D9%88%DB%8C%D8%B3-%D8%A8%D9%87%D8%AF%D8%A7%D8%B4%D8%AA%DB%8C/%D8%AA%D9%88%D8%A7%D9%84%D8%AA-%D9%81%D8%B1%D9%86%DA%AF%DB%8C/%D9%81%D8%B1%D9%86%DA%AF%DB%8C-%D9%85%D8%B1%D9%88%D8%A7%D8%B1%DB%8C%D8%AF/

**Comment by demirmu** [comment]
"Clickable elements too close together". I Have Same problem in my site. Anyone help me.
<a href="https://kurteknoloji.com/">/a>

**Comment by javadth** [comment]
added margin:1px; to my style for a, but not solved
also added line height but couldn't solve it 

what should I do?
here :
https://camera-price.com

and : https://engclubs.net/%d8%ae%d8%af%d9%85%d8%a7%d8%aa-%d9%86%d9%82%d8%b4%d9%87-%d8%a8%d8%b1%d8%af%d8%a7%d8%b1%db%8c-%d8%aa%d9%87%d8%b1%d8%a7%d9%86

**Comment by apeiron24** [comment]
I am having the same issue. Even google support forum could not give a tangible answer to the problem. Ha ha! So Our giant Great Github geniuses can not even help us too. Lmao

**Comment by m-akbari11** [comment]
Content wider ? 
if Your Content Wider Than Screen, You Solve this Probblem with Css .


https://Fanoos724.com

**Comment by arijitshil12345** [comment]
Clickable elements too close together (solved) - https://www.xpresstv.in/clickable-elements-too-close-together-content-wider-than-screen-text-too-small-to-read-solved/
Solve the issue in 2 minits
