### ISSUE TITLE
Clickable elements too close together and Content wider than screen

### ISSUE THREAD

**Issue by rajukaushik94** [pstephens/kingjames.bible#45]
hi am using bridge wordpress theme.
Am checking in console no issue found. website is fully responsive on mobile device.
but when am checking in webmaster it show 2 error "Clickable elements too close together" and "Content wider than screen".
I had update  line-height & margin but issue are same.
Please help me to fix out this for my website.

**Comment by pstephens** [comment]
This issue does not appear to be related to kingjames.bible, closing.
